
## Icebreaker and IceSugar RSMB5 project - RV32I for Lattice iCE40
## With complete open-source toolchain flow using:
## -> yosys 
## -> icarus verilog
## -> icestorm project
## 
## Tests are written in several languages
## -> Systemverilog Pure Testbench (Vivado)
## -> UVM testbench (Vivado)
## -> PyUvm (Icarus)
## -> Formal either using SVA and PSL (Vivado) or cuncurrent assertions with Yosys
## 
## Copyright (c) 2021 Raffaele Signoriello (raff.signoriello92@gmail.com)
## 
## Permission is hereby granted, free of charge, to any person obtaining a 
## copy of this software and associated documentation files (the "Software"), 
## to deal in the Software without restriction, including without limitation 
## the rights to use, copy, modify, merge, publish, distribute, sublicense, 
## and/or sell copies of the Software, and to permit persons to whom the 
## Software is furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice shall be included 
## in all copies or substantial portions of the Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
## EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
## MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
## IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
## CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
## TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
## SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

## This file contains register parameters and is autogenerated

regfile_apb_rif = 0x0
register_data1 = 0x0
register_data2 = 0x4
register_data3 = 0x8
register_write_enable = 0xc
register_data_status_1 = 0x10
register_data_status_2 = 0x14
register_data_status_3 = 0x18
memory_adress_start = 0x100
register_r1_0 = 0x100
register_r1_1 = 0x104
register_r1_2 = 0x108
register_r1_3 = 0x10c
register_r1_4 = 0x110
register_r1_5 = 0x114
register_r1_6 = 0x118
register_r1_7 = 0x11c
register_r1_8 = 0x120
register_r1_9 = 0x124
register_r1_10 = 0x128
register_r1_11 = 0x12c
register_r1_12 = 0x130
register_r1_13 = 0x134
register_r1_14 = 0x138
register_r1_15 = 0x13c
register_r1_16 = 0x140
register_r1_17 = 0x144
register_r1_18 = 0x148
register_r1_19 = 0x14c
register_r1_20 = 0x150
register_r1_21 = 0x154
register_r1_22 = 0x158
register_r1_23 = 0x15c
register_r1_24 = 0x160
register_r1_25 = 0x164
register_r1_26 = 0x168
register_r1_27 = 0x16c
register_r1_28 = 0x170
register_r1_29 = 0x174
register_r1_30 = 0x178
register_r1_31 = 0x17c
register_r1_32 = 0x180
register_r1_33 = 0x184
register_r1_34 = 0x188
register_r1_35 = 0x18c
register_r1_36 = 0x190
register_r1_37 = 0x194
register_r1_38 = 0x198
register_r1_39 = 0x19c
register_r1_40 = 0x1a0
register_r1_41 = 0x1a4
register_r1_42 = 0x1a8
register_r1_43 = 0x1ac
register_r1_44 = 0x1b0
register_r1_45 = 0x1b4
register_r1_46 = 0x1b8
register_r1_47 = 0x1bc
register_r1_48 = 0x1c0
register_r1_49 = 0x1c4
register_r1_50 = 0x1c8
register_r1_51 = 0x1cc
register_r1_52 = 0x1d0
register_r1_53 = 0x1d4
register_r1_54 = 0x1d8
register_r1_55 = 0x1dc
register_r1_56 = 0x1e0
register_r1_57 = 0x1e4
register_r1_58 = 0x1e8
register_r1_59 = 0x1ec
register_r1_60 = 0x1f0
register_r1_61 = 0x1f4
register_r1_62 = 0x1f8
register_r1_63 = 0x1fc
register_r1_64 = 0x200
register_r1_65 = 0x204
register_r1_66 = 0x208
register_r1_67 = 0x20c
register_r1_68 = 0x210
register_r1_69 = 0x214
register_r1_70 = 0x218
register_r1_71 = 0x21c
register_r1_72 = 0x220
register_r1_73 = 0x224
register_r1_74 = 0x228
register_r1_75 = 0x22c
register_r1_76 = 0x230
register_r1_77 = 0x234
register_r1_78 = 0x238
register_r1_79 = 0x23c
register_r1_80 = 0x240
register_r1_81 = 0x244
register_r1_82 = 0x248
register_r1_83 = 0x24c
register_r1_84 = 0x250
register_r1_85 = 0x254
register_r1_86 = 0x258
register_r1_87 = 0x25c
register_r1_88 = 0x260
register_r1_89 = 0x264
register_r1_90 = 0x268
register_r1_91 = 0x26c
register_r1_92 = 0x270
register_r1_93 = 0x274
register_r1_94 = 0x278
register_r1_95 = 0x27c
register_r1_96 = 0x280
register_r1_97 = 0x284
register_r1_98 = 0x288
register_r1_99 = 0x28c
register_r1_100 = 0x290
register_r1_101 = 0x294
register_r1_102 = 0x298
register_r1_103 = 0x29c
register_r1_104 = 0x2a0
register_r1_105 = 0x2a4
register_r1_106 = 0x2a8
register_r1_107 = 0x2ac
register_r1_108 = 0x2b0
register_r1_109 = 0x2b4
register_r1_110 = 0x2b8
register_r1_111 = 0x2bc
register_r1_112 = 0x2c0
register_r1_113 = 0x2c4
register_r1_114 = 0x2c8
register_r1_115 = 0x2cc
register_r1_116 = 0x2d0
register_r1_117 = 0x2d4
register_r1_118 = 0x2d8
register_r1_119 = 0x2dc
register_r1_120 = 0x2e0
register_r1_121 = 0x2e4
register_r1_122 = 0x2e8
register_r1_123 = 0x2ec
register_r1_124 = 0x2f0
register_r1_125 = 0x2f4
register_r1_126 = 0x2f8
register_r1_127 = 0x2fc
register_r1_128 = 0x300
register_r1_129 = 0x304
register_r1_130 = 0x308
register_r1_131 = 0x30c
register_r1_132 = 0x310
register_r1_133 = 0x314
register_r1_134 = 0x318
register_r1_135 = 0x31c
register_r1_136 = 0x320
register_r1_137 = 0x324
register_r1_138 = 0x328
register_r1_139 = 0x32c
register_r1_140 = 0x330
register_r1_141 = 0x334
register_r1_142 = 0x338
register_r1_143 = 0x33c
register_r1_144 = 0x340
register_r1_145 = 0x344
register_r1_146 = 0x348
register_r1_147 = 0x34c
register_r1_148 = 0x350
register_r1_149 = 0x354
register_r1_150 = 0x358
register_r1_151 = 0x35c
register_r1_152 = 0x360
register_r1_153 = 0x364
register_r1_154 = 0x368
register_r1_155 = 0x36c
register_r1_156 = 0x370
register_r1_157 = 0x374
register_r1_158 = 0x378
register_r1_159 = 0x37c
register_r1_160 = 0x380
register_r1_161 = 0x384
register_r1_162 = 0x388
register_r1_163 = 0x38c
register_r1_164 = 0x390
register_r1_165 = 0x394
register_r1_166 = 0x398
register_r1_167 = 0x39c
register_r1_168 = 0x3a0
register_r1_169 = 0x3a4
register_r1_170 = 0x3a8
register_r1_171 = 0x3ac
register_r1_172 = 0x3b0
register_r1_173 = 0x3b4
register_r1_174 = 0x3b8
register_r1_175 = 0x3bc
register_r1_176 = 0x3c0
register_r1_177 = 0x3c4
register_r1_178 = 0x3c8
register_r1_179 = 0x3cc
register_r1_180 = 0x3d0
register_r1_181 = 0x3d4
register_r1_182 = 0x3d8
register_r1_183 = 0x3dc
register_r1_184 = 0x3e0
register_r1_185 = 0x3e4
register_r1_186 = 0x3e8
register_r1_187 = 0x3ec
register_r1_188 = 0x3f0
register_r1_189 = 0x3f4
register_r1_190 = 0x3f8
register_r1_191 = 0x3fc
register_r1_192 = 0x400
register_r1_193 = 0x404
register_r1_194 = 0x408
register_r1_195 = 0x40c
register_r1_196 = 0x410
register_r1_197 = 0x414
register_r1_198 = 0x418
register_r1_199 = 0x41c
register_r1_200 = 0x420
register_r1_201 = 0x424
register_r1_202 = 0x428
register_r1_203 = 0x42c
register_r1_204 = 0x430
register_r1_205 = 0x434
register_r1_206 = 0x438
register_r1_207 = 0x43c
register_r1_208 = 0x440
register_r1_209 = 0x444
register_r1_210 = 0x448
register_r1_211 = 0x44c
register_r1_212 = 0x450
register_r1_213 = 0x454
register_r1_214 = 0x458
register_r1_215 = 0x45c
register_r1_216 = 0x460
register_r1_217 = 0x464
register_r1_218 = 0x468
register_r1_219 = 0x46c
register_r1_220 = 0x470
register_r1_221 = 0x474
register_r1_222 = 0x478
register_r1_223 = 0x47c
register_r1_224 = 0x480
register_r1_225 = 0x484
register_r1_226 = 0x488
register_r1_227 = 0x48c
register_r1_228 = 0x490
register_r1_229 = 0x494
register_r1_230 = 0x498
register_r1_231 = 0x49c
register_r1_232 = 0x4a0
register_r1_233 = 0x4a4
register_r1_234 = 0x4a8
register_r1_235 = 0x4ac
register_r1_236 = 0x4b0
register_r1_237 = 0x4b4
register_r1_238 = 0x4b8
register_r1_239 = 0x4bc
register_r1_240 = 0x4c0
register_r1_241 = 0x4c4
register_r1_242 = 0x4c8
register_r1_243 = 0x4cc
register_r1_244 = 0x4d0
register_r1_245 = 0x4d4
register_r1_246 = 0x4d8
register_r1_247 = 0x4dc
register_r1_248 = 0x4e0
register_r1_249 = 0x4e4
register_r1_250 = 0x4e8
register_r1_251 = 0x4ec
register_r1_252 = 0x4f0
register_r1_253 = 0x4f4
register_r1_254 = 0x4f8
register_r1_255 = 0x4fc
memory_adress_end = 0x4fc
mask_hwwr_apb_rif = 0x0
mask_hwwr_data1 = 0x0
mask_hwwr_data2 = 0x0
mask_hwwr_data3 = 0x0
mask_hwwr_write_enable = 0x1
mask_hwwr_data_status_1 = 0x1
mask_hwwr_data_status_2 = 0x1
mask_hwrd_apb_rif = 0xffffffff
mask_hwrd_data1 = 0xffffffff
mask_hwrd_data2 = 0xffffffff
mask_hwrd_data3 = 0x7
mask_hwrd_write_enable = 0x0
mask_hwrd_data_status_1 = 0x0
mask_hwrd_data_status_2 = 0x0
mask_swwr_apb_rif = 0xffffffff
mask_swwr_data1 = 0xffffffff
mask_swwr_data2 = 0xffffffff
mask_swwr_data3 = 0x7
mask_swwr_write_enable = 0x0
mask_swwr_data_status_1 = 0x0
mask_swwr_data_status_2 = 0x0
mask_swrd_apb_rif = 0xffffffff
mask_swrd_data1 = 0xffffffff
mask_swrd_data2 = 0xffffffff
mask_swrd_data3 = 0x0
mask_swrd_write_enable = 0x1
mask_swrd_data_status_1 = 0x1
mask_swrd_data_status_2 = 0x1
apb_rif_POR_VALUE = 0x0
data1_POR_VALUE = 0x0
data2_POR_VALUE = 0x0
data3_POR_VALUE = 0x0
write_enable_POR_VALUE = 0x0
data_status_1_POR_VALUE = 0x0
data_status_2_POR_VALUE = 0x0
