/*
 Icebreaker and IceSugar RSMB5 project - RV32I for Lattice iCE40
 With complete open-source toolchain flow using:
 -> yosys 
 -> icarus verilog
 -> icestorm project

 Tests are written in several languages
 -> Systemverilog Pure Testbench (Vivado)
 -> UVM testbench (Vivado)
 -> PyUvm (Icarus)
 -> Formal either using SVA and PSL (Vivado) or cuncurrent assertions with Yosys

 Copyright (c) 2021 Raffaele Signoriello (raff.signoriello92@gmail.com)

 Permission is hereby granted, free of charge, to any person obtaining a 
 copy of this software and associated documentation files (the "Software"), 
 to deal in the Software without restriction, including without limitation 
 the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 and/or sell copies of the Software, and to permit persons to whom the 
 Software is furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included 
 in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
 CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
 TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/* 
  This file contains register parameters and is autogenerated
*/
parameter regfile_apb_rif = 32'h0;
parameter register_data1 = 32'h0;
parameter register_data2 = 32'h4;
parameter register_data3 = 32'h8;
parameter register_write_enable = 32'hc;
parameter register_data_status_1 = 32'h10;
parameter register_data_status_2 = 32'h14;
parameter register_data_status_3 = 32'h18;
parameter memory_adress_start = 32'h100;
parameter register_r1_0 = 32'h100;
parameter register_r1_1 = 32'h104;
parameter register_r1_2 = 32'h108;
parameter register_r1_3 = 32'h10c;
parameter register_r1_4 = 32'h110;
parameter register_r1_5 = 32'h114;
parameter register_r1_6 = 32'h118;
parameter register_r1_7 = 32'h11c;
parameter register_r1_8 = 32'h120;
parameter register_r1_9 = 32'h124;
parameter register_r1_10 = 32'h128;
parameter register_r1_11 = 32'h12c;
parameter register_r1_12 = 32'h130;
parameter register_r1_13 = 32'h134;
parameter register_r1_14 = 32'h138;
parameter register_r1_15 = 32'h13c;
parameter register_r1_16 = 32'h140;
parameter register_r1_17 = 32'h144;
parameter register_r1_18 = 32'h148;
parameter register_r1_19 = 32'h14c;
parameter register_r1_20 = 32'h150;
parameter register_r1_21 = 32'h154;
parameter register_r1_22 = 32'h158;
parameter register_r1_23 = 32'h15c;
parameter register_r1_24 = 32'h160;
parameter register_r1_25 = 32'h164;
parameter register_r1_26 = 32'h168;
parameter register_r1_27 = 32'h16c;
parameter register_r1_28 = 32'h170;
parameter register_r1_29 = 32'h174;
parameter register_r1_30 = 32'h178;
parameter register_r1_31 = 32'h17c;
parameter register_r1_32 = 32'h180;
parameter register_r1_33 = 32'h184;
parameter register_r1_34 = 32'h188;
parameter register_r1_35 = 32'h18c;
parameter register_r1_36 = 32'h190;
parameter register_r1_37 = 32'h194;
parameter register_r1_38 = 32'h198;
parameter register_r1_39 = 32'h19c;
parameter register_r1_40 = 32'h1a0;
parameter register_r1_41 = 32'h1a4;
parameter register_r1_42 = 32'h1a8;
parameter register_r1_43 = 32'h1ac;
parameter register_r1_44 = 32'h1b0;
parameter register_r1_45 = 32'h1b4;
parameter register_r1_46 = 32'h1b8;
parameter register_r1_47 = 32'h1bc;
parameter register_r1_48 = 32'h1c0;
parameter register_r1_49 = 32'h1c4;
parameter register_r1_50 = 32'h1c8;
parameter register_r1_51 = 32'h1cc;
parameter register_r1_52 = 32'h1d0;
parameter register_r1_53 = 32'h1d4;
parameter register_r1_54 = 32'h1d8;
parameter register_r1_55 = 32'h1dc;
parameter register_r1_56 = 32'h1e0;
parameter register_r1_57 = 32'h1e4;
parameter register_r1_58 = 32'h1e8;
parameter register_r1_59 = 32'h1ec;
parameter register_r1_60 = 32'h1f0;
parameter register_r1_61 = 32'h1f4;
parameter register_r1_62 = 32'h1f8;
parameter register_r1_63 = 32'h1fc;
parameter register_r1_64 = 32'h200;
parameter register_r1_65 = 32'h204;
parameter register_r1_66 = 32'h208;
parameter register_r1_67 = 32'h20c;
parameter register_r1_68 = 32'h210;
parameter register_r1_69 = 32'h214;
parameter register_r1_70 = 32'h218;
parameter register_r1_71 = 32'h21c;
parameter register_r1_72 = 32'h220;
parameter register_r1_73 = 32'h224;
parameter register_r1_74 = 32'h228;
parameter register_r1_75 = 32'h22c;
parameter register_r1_76 = 32'h230;
parameter register_r1_77 = 32'h234;
parameter register_r1_78 = 32'h238;
parameter register_r1_79 = 32'h23c;
parameter register_r1_80 = 32'h240;
parameter register_r1_81 = 32'h244;
parameter register_r1_82 = 32'h248;
parameter register_r1_83 = 32'h24c;
parameter register_r1_84 = 32'h250;
parameter register_r1_85 = 32'h254;
parameter register_r1_86 = 32'h258;
parameter register_r1_87 = 32'h25c;
parameter register_r1_88 = 32'h260;
parameter register_r1_89 = 32'h264;
parameter register_r1_90 = 32'h268;
parameter register_r1_91 = 32'h26c;
parameter register_r1_92 = 32'h270;
parameter register_r1_93 = 32'h274;
parameter register_r1_94 = 32'h278;
parameter register_r1_95 = 32'h27c;
parameter register_r1_96 = 32'h280;
parameter register_r1_97 = 32'h284;
parameter register_r1_98 = 32'h288;
parameter register_r1_99 = 32'h28c;
parameter register_r1_100 = 32'h290;
parameter register_r1_101 = 32'h294;
parameter register_r1_102 = 32'h298;
parameter register_r1_103 = 32'h29c;
parameter register_r1_104 = 32'h2a0;
parameter register_r1_105 = 32'h2a4;
parameter register_r1_106 = 32'h2a8;
parameter register_r1_107 = 32'h2ac;
parameter register_r1_108 = 32'h2b0;
parameter register_r1_109 = 32'h2b4;
parameter register_r1_110 = 32'h2b8;
parameter register_r1_111 = 32'h2bc;
parameter register_r1_112 = 32'h2c0;
parameter register_r1_113 = 32'h2c4;
parameter register_r1_114 = 32'h2c8;
parameter register_r1_115 = 32'h2cc;
parameter register_r1_116 = 32'h2d0;
parameter register_r1_117 = 32'h2d4;
parameter register_r1_118 = 32'h2d8;
parameter register_r1_119 = 32'h2dc;
parameter register_r1_120 = 32'h2e0;
parameter register_r1_121 = 32'h2e4;
parameter register_r1_122 = 32'h2e8;
parameter register_r1_123 = 32'h2ec;
parameter register_r1_124 = 32'h2f0;
parameter register_r1_125 = 32'h2f4;
parameter register_r1_126 = 32'h2f8;
parameter register_r1_127 = 32'h2fc;
parameter register_r1_128 = 32'h300;
parameter register_r1_129 = 32'h304;
parameter register_r1_130 = 32'h308;
parameter register_r1_131 = 32'h30c;
parameter register_r1_132 = 32'h310;
parameter register_r1_133 = 32'h314;
parameter register_r1_134 = 32'h318;
parameter register_r1_135 = 32'h31c;
parameter register_r1_136 = 32'h320;
parameter register_r1_137 = 32'h324;
parameter register_r1_138 = 32'h328;
parameter register_r1_139 = 32'h32c;
parameter register_r1_140 = 32'h330;
parameter register_r1_141 = 32'h334;
parameter register_r1_142 = 32'h338;
parameter register_r1_143 = 32'h33c;
parameter register_r1_144 = 32'h340;
parameter register_r1_145 = 32'h344;
parameter register_r1_146 = 32'h348;
parameter register_r1_147 = 32'h34c;
parameter register_r1_148 = 32'h350;
parameter register_r1_149 = 32'h354;
parameter register_r1_150 = 32'h358;
parameter register_r1_151 = 32'h35c;
parameter register_r1_152 = 32'h360;
parameter register_r1_153 = 32'h364;
parameter register_r1_154 = 32'h368;
parameter register_r1_155 = 32'h36c;
parameter register_r1_156 = 32'h370;
parameter register_r1_157 = 32'h374;
parameter register_r1_158 = 32'h378;
parameter register_r1_159 = 32'h37c;
parameter register_r1_160 = 32'h380;
parameter register_r1_161 = 32'h384;
parameter register_r1_162 = 32'h388;
parameter register_r1_163 = 32'h38c;
parameter register_r1_164 = 32'h390;
parameter register_r1_165 = 32'h394;
parameter register_r1_166 = 32'h398;
parameter register_r1_167 = 32'h39c;
parameter register_r1_168 = 32'h3a0;
parameter register_r1_169 = 32'h3a4;
parameter register_r1_170 = 32'h3a8;
parameter register_r1_171 = 32'h3ac;
parameter register_r1_172 = 32'h3b0;
parameter register_r1_173 = 32'h3b4;
parameter register_r1_174 = 32'h3b8;
parameter register_r1_175 = 32'h3bc;
parameter register_r1_176 = 32'h3c0;
parameter register_r1_177 = 32'h3c4;
parameter register_r1_178 = 32'h3c8;
parameter register_r1_179 = 32'h3cc;
parameter register_r1_180 = 32'h3d0;
parameter register_r1_181 = 32'h3d4;
parameter register_r1_182 = 32'h3d8;
parameter register_r1_183 = 32'h3dc;
parameter register_r1_184 = 32'h3e0;
parameter register_r1_185 = 32'h3e4;
parameter register_r1_186 = 32'h3e8;
parameter register_r1_187 = 32'h3ec;
parameter register_r1_188 = 32'h3f0;
parameter register_r1_189 = 32'h3f4;
parameter register_r1_190 = 32'h3f8;
parameter register_r1_191 = 32'h3fc;
parameter register_r1_192 = 32'h400;
parameter register_r1_193 = 32'h404;
parameter register_r1_194 = 32'h408;
parameter register_r1_195 = 32'h40c;
parameter register_r1_196 = 32'h410;
parameter register_r1_197 = 32'h414;
parameter register_r1_198 = 32'h418;
parameter register_r1_199 = 32'h41c;
parameter register_r1_200 = 32'h420;
parameter register_r1_201 = 32'h424;
parameter register_r1_202 = 32'h428;
parameter register_r1_203 = 32'h42c;
parameter register_r1_204 = 32'h430;
parameter register_r1_205 = 32'h434;
parameter register_r1_206 = 32'h438;
parameter register_r1_207 = 32'h43c;
parameter register_r1_208 = 32'h440;
parameter register_r1_209 = 32'h444;
parameter register_r1_210 = 32'h448;
parameter register_r1_211 = 32'h44c;
parameter register_r1_212 = 32'h450;
parameter register_r1_213 = 32'h454;
parameter register_r1_214 = 32'h458;
parameter register_r1_215 = 32'h45c;
parameter register_r1_216 = 32'h460;
parameter register_r1_217 = 32'h464;
parameter register_r1_218 = 32'h468;
parameter register_r1_219 = 32'h46c;
parameter register_r1_220 = 32'h470;
parameter register_r1_221 = 32'h474;
parameter register_r1_222 = 32'h478;
parameter register_r1_223 = 32'h47c;
parameter register_r1_224 = 32'h480;
parameter register_r1_225 = 32'h484;
parameter register_r1_226 = 32'h488;
parameter register_r1_227 = 32'h48c;
parameter register_r1_228 = 32'h490;
parameter register_r1_229 = 32'h494;
parameter register_r1_230 = 32'h498;
parameter register_r1_231 = 32'h49c;
parameter register_r1_232 = 32'h4a0;
parameter register_r1_233 = 32'h4a4;
parameter register_r1_234 = 32'h4a8;
parameter register_r1_235 = 32'h4ac;
parameter register_r1_236 = 32'h4b0;
parameter register_r1_237 = 32'h4b4;
parameter register_r1_238 = 32'h4b8;
parameter register_r1_239 = 32'h4bc;
parameter register_r1_240 = 32'h4c0;
parameter register_r1_241 = 32'h4c4;
parameter register_r1_242 = 32'h4c8;
parameter register_r1_243 = 32'h4cc;
parameter register_r1_244 = 32'h4d0;
parameter register_r1_245 = 32'h4d4;
parameter register_r1_246 = 32'h4d8;
parameter register_r1_247 = 32'h4dc;
parameter register_r1_248 = 32'h4e0;
parameter register_r1_249 = 32'h4e4;
parameter register_r1_250 = 32'h4e8;
parameter register_r1_251 = 32'h4ec;
parameter register_r1_252 = 32'h4f0;
parameter register_r1_253 = 32'h4f4;
parameter register_r1_254 = 32'h4f8;
parameter register_r1_255 = 32'h4fc;
parameter memory_adress_end = 32'h4fc;
`define regfile_apb_rif  32'h0
`define register_data1  32'h0
`define register_data2  32'h4
`define register_data3  32'h8
`define register_write_enable  32'hc
`define register_data_status_1  32'h10
`define register_data_status_2  32'h14
`define register_data_status_3  32'h18
`define memory_adress_start  32'h100
`define register_r1_0  32'h100
`define register_r1_1  32'h104
`define register_r1_2  32'h108
`define register_r1_3  32'h10c
`define register_r1_4  32'h110
`define register_r1_5  32'h114
`define register_r1_6  32'h118
`define register_r1_7  32'h11c
`define register_r1_8  32'h120
`define register_r1_9  32'h124
`define register_r1_10  32'h128
`define register_r1_11  32'h12c
`define register_r1_12  32'h130
`define register_r1_13  32'h134
`define register_r1_14  32'h138
`define register_r1_15  32'h13c
`define register_r1_16  32'h140
`define register_r1_17  32'h144
`define register_r1_18  32'h148
`define register_r1_19  32'h14c
`define register_r1_20  32'h150
`define register_r1_21  32'h154
`define register_r1_22  32'h158
`define register_r1_23  32'h15c
`define register_r1_24  32'h160
`define register_r1_25  32'h164
`define register_r1_26  32'h168
`define register_r1_27  32'h16c
`define register_r1_28  32'h170
`define register_r1_29  32'h174
`define register_r1_30  32'h178
`define register_r1_31  32'h17c
`define register_r1_32  32'h180
`define register_r1_33  32'h184
`define register_r1_34  32'h188
`define register_r1_35  32'h18c
`define register_r1_36  32'h190
`define register_r1_37  32'h194
`define register_r1_38  32'h198
`define register_r1_39  32'h19c
`define register_r1_40  32'h1a0
`define register_r1_41  32'h1a4
`define register_r1_42  32'h1a8
`define register_r1_43  32'h1ac
`define register_r1_44  32'h1b0
`define register_r1_45  32'h1b4
`define register_r1_46  32'h1b8
`define register_r1_47  32'h1bc
`define register_r1_48  32'h1c0
`define register_r1_49  32'h1c4
`define register_r1_50  32'h1c8
`define register_r1_51  32'h1cc
`define register_r1_52  32'h1d0
`define register_r1_53  32'h1d4
`define register_r1_54  32'h1d8
`define register_r1_55  32'h1dc
`define register_r1_56  32'h1e0
`define register_r1_57  32'h1e4
`define register_r1_58  32'h1e8
`define register_r1_59  32'h1ec
`define register_r1_60  32'h1f0
`define register_r1_61  32'h1f4
`define register_r1_62  32'h1f8
`define register_r1_63  32'h1fc
`define register_r1_64  32'h200
`define register_r1_65  32'h204
`define register_r1_66  32'h208
`define register_r1_67  32'h20c
`define register_r1_68  32'h210
`define register_r1_69  32'h214
`define register_r1_70  32'h218
`define register_r1_71  32'h21c
`define register_r1_72  32'h220
`define register_r1_73  32'h224
`define register_r1_74  32'h228
`define register_r1_75  32'h22c
`define register_r1_76  32'h230
`define register_r1_77  32'h234
`define register_r1_78  32'h238
`define register_r1_79  32'h23c
`define register_r1_80  32'h240
`define register_r1_81  32'h244
`define register_r1_82  32'h248
`define register_r1_83  32'h24c
`define register_r1_84  32'h250
`define register_r1_85  32'h254
`define register_r1_86  32'h258
`define register_r1_87  32'h25c
`define register_r1_88  32'h260
`define register_r1_89  32'h264
`define register_r1_90  32'h268
`define register_r1_91  32'h26c
`define register_r1_92  32'h270
`define register_r1_93  32'h274
`define register_r1_94  32'h278
`define register_r1_95  32'h27c
`define register_r1_96  32'h280
`define register_r1_97  32'h284
`define register_r1_98  32'h288
`define register_r1_99  32'h28c
`define register_r1_100  32'h290
`define register_r1_101  32'h294
`define register_r1_102  32'h298
`define register_r1_103  32'h29c
`define register_r1_104  32'h2a0
`define register_r1_105  32'h2a4
`define register_r1_106  32'h2a8
`define register_r1_107  32'h2ac
`define register_r1_108  32'h2b0
`define register_r1_109  32'h2b4
`define register_r1_110  32'h2b8
`define register_r1_111  32'h2bc
`define register_r1_112  32'h2c0
`define register_r1_113  32'h2c4
`define register_r1_114  32'h2c8
`define register_r1_115  32'h2cc
`define register_r1_116  32'h2d0
`define register_r1_117  32'h2d4
`define register_r1_118  32'h2d8
`define register_r1_119  32'h2dc
`define register_r1_120  32'h2e0
`define register_r1_121  32'h2e4
`define register_r1_122  32'h2e8
`define register_r1_123  32'h2ec
`define register_r1_124  32'h2f0
`define register_r1_125  32'h2f4
`define register_r1_126  32'h2f8
`define register_r1_127  32'h2fc
`define register_r1_128  32'h300
`define register_r1_129  32'h304
`define register_r1_130  32'h308
`define register_r1_131  32'h30c
`define register_r1_132  32'h310
`define register_r1_133  32'h314
`define register_r1_134  32'h318
`define register_r1_135  32'h31c
`define register_r1_136  32'h320
`define register_r1_137  32'h324
`define register_r1_138  32'h328
`define register_r1_139  32'h32c
`define register_r1_140  32'h330
`define register_r1_141  32'h334
`define register_r1_142  32'h338
`define register_r1_143  32'h33c
`define register_r1_144  32'h340
`define register_r1_145  32'h344
`define register_r1_146  32'h348
`define register_r1_147  32'h34c
`define register_r1_148  32'h350
`define register_r1_149  32'h354
`define register_r1_150  32'h358
`define register_r1_151  32'h35c
`define register_r1_152  32'h360
`define register_r1_153  32'h364
`define register_r1_154  32'h368
`define register_r1_155  32'h36c
`define register_r1_156  32'h370
`define register_r1_157  32'h374
`define register_r1_158  32'h378
`define register_r1_159  32'h37c
`define register_r1_160  32'h380
`define register_r1_161  32'h384
`define register_r1_162  32'h388
`define register_r1_163  32'h38c
`define register_r1_164  32'h390
`define register_r1_165  32'h394
`define register_r1_166  32'h398
`define register_r1_167  32'h39c
`define register_r1_168  32'h3a0
`define register_r1_169  32'h3a4
`define register_r1_170  32'h3a8
`define register_r1_171  32'h3ac
`define register_r1_172  32'h3b0
`define register_r1_173  32'h3b4
`define register_r1_174  32'h3b8
`define register_r1_175  32'h3bc
`define register_r1_176  32'h3c0
`define register_r1_177  32'h3c4
`define register_r1_178  32'h3c8
`define register_r1_179  32'h3cc
`define register_r1_180  32'h3d0
`define register_r1_181  32'h3d4
`define register_r1_182  32'h3d8
`define register_r1_183  32'h3dc
`define register_r1_184  32'h3e0
`define register_r1_185  32'h3e4
`define register_r1_186  32'h3e8
`define register_r1_187  32'h3ec
`define register_r1_188  32'h3f0
`define register_r1_189  32'h3f4
`define register_r1_190  32'h3f8
`define register_r1_191  32'h3fc
`define register_r1_192  32'h400
`define register_r1_193  32'h404
`define register_r1_194  32'h408
`define register_r1_195  32'h40c
`define register_r1_196  32'h410
`define register_r1_197  32'h414
`define register_r1_198  32'h418
`define register_r1_199  32'h41c
`define register_r1_200  32'h420
`define register_r1_201  32'h424
`define register_r1_202  32'h428
`define register_r1_203  32'h42c
`define register_r1_204  32'h430
`define register_r1_205  32'h434
`define register_r1_206  32'h438
`define register_r1_207  32'h43c
`define register_r1_208  32'h440
`define register_r1_209  32'h444
`define register_r1_210  32'h448
`define register_r1_211  32'h44c
`define register_r1_212  32'h450
`define register_r1_213  32'h454
`define register_r1_214  32'h458
`define register_r1_215  32'h45c
`define register_r1_216  32'h460
`define register_r1_217  32'h464
`define register_r1_218  32'h468
`define register_r1_219  32'h46c
`define register_r1_220  32'h470
`define register_r1_221  32'h474
`define register_r1_222  32'h478
`define register_r1_223  32'h47c
`define register_r1_224  32'h480
`define register_r1_225  32'h484
`define register_r1_226  32'h488
`define register_r1_227  32'h48c
`define register_r1_228  32'h490
`define register_r1_229  32'h494
`define register_r1_230  32'h498
`define register_r1_231  32'h49c
`define register_r1_232  32'h4a0
`define register_r1_233  32'h4a4
`define register_r1_234  32'h4a8
`define register_r1_235  32'h4ac
`define register_r1_236  32'h4b0
`define register_r1_237  32'h4b4
`define register_r1_238  32'h4b8
`define register_r1_239  32'h4bc
`define register_r1_240  32'h4c0
`define register_r1_241  32'h4c4
`define register_r1_242  32'h4c8
`define register_r1_243  32'h4cc
`define register_r1_244  32'h4d0
`define register_r1_245  32'h4d4
`define register_r1_246  32'h4d8
`define register_r1_247  32'h4dc
`define register_r1_248  32'h4e0
`define register_r1_249  32'h4e4
`define register_r1_250  32'h4e8
`define register_r1_251  32'h4ec
`define register_r1_252  32'h4f0
`define register_r1_253  32'h4f4
`define register_r1_254  32'h4f8
`define register_r1_255  32'h4fc
`define memory_adress_end  32'h4fc
`define mask_hwwr_apb_rif  32'h0
`define mask_hwwr_data1  32'h0
`define mask_hwwr_data2  32'h0
`define mask_hwwr_data3  32'h0
`define mask_hwwr_write_enable  32'h1
`define mask_hwwr_data_status_1  32'h1
`define mask_hwwr_data_status_2  32'h1
`define mask_hwrd_apb_rif  32'hffffffff
`define mask_hwrd_data1  32'hffffffff
`define mask_hwrd_data2  32'hffffffff
`define mask_hwrd_data3  32'h7
`define mask_hwrd_write_enable  32'h0
`define mask_hwrd_data_status_1  32'h0
`define mask_hwrd_data_status_2  32'h0
`define mask_swwr_apb_rif  32'hffffffff
`define mask_swwr_data1  32'hffffffff
`define mask_swwr_data2  32'hffffffff
`define mask_swwr_data3  32'h7
`define mask_swwr_write_enable  32'h0
`define mask_swwr_data_status_1  32'h0
`define mask_swwr_data_status_2  32'h0
`define mask_swrd_apb_rif  32'hffffffff
`define mask_swrd_data1  32'hffffffff
`define mask_swrd_data2  32'hffffffff
`define mask_swrd_data3  32'h0
`define mask_swrd_write_enable  32'h1
`define mask_swrd_data_status_1  32'h1
`define mask_swrd_data_status_2  32'h1
`define apb_rif_POR_VALUE  32'h0
`define data1_POR_VALUE  32'h0
`define data2_POR_VALUE  32'h0
`define data3_POR_VALUE  32'h0
`define write_enable_POR_VALUE  32'h0
`define data_status_1_POR_VALUE  32'h0
`define data_status_2_POR_VALUE  32'h0
