/*
 Icebreaker and IceSugar RSMB5 project - RV32I for Lattice iCE40
 With complete open-source toolchain flow using:
 -> yosys 
 -> icarus verilog
 -> icestorm project

 Tests are written in several languages
 -> Systemverilog Pure Testbench (Vivado)
 -> UVM testbench (Vivado)
 -> PyUvm (Icarus)
 -> Formal either using SVA and PSL (Vivado) or cuncurrent assertions with Yosys

 Copyright (c) 2021 Raffaele Signoriello (raff.signoriello92@gmail.com)

 Permission is hereby granted, free of charge, to any person obtaining a 
 copy of this software and associated documentation files (the "Software"), 
 to deal in the Software without restriction, including without limitation 
 the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 and/or sell copies of the Software, and to permit persons to whom the 
 Software is furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included 
 in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
 IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY 
 CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, 
 TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/* 
  This file contains register parameters and is autogenerated
*/
parameter regfile_apb_rif = 32'h0;
parameter register_data1 = 32'h0;
parameter register_data2 = 32'h4;
parameter register_data3 = 32'h8;
parameter register_write_enable = 32'hc;
parameter register_data_status_1 = 32'h10;
parameter register_data_status_2 = 32'h14;
parameter register_data_status_3 = 32'h18;
parameter memory_adress_start = 32'h100;
parameter register_r1_0 = 32'h100;
parameter register_r1_1 = 32'h180;
parameter register_r1_2 = 32'h200;
parameter register_r1_3 = 32'h280;
parameter register_r1_4 = 32'h300;
parameter register_r1_5 = 32'h380;
parameter register_r1_6 = 32'h400;
parameter register_r1_7 = 32'h480;
parameter register_r1_8 = 32'h500;
parameter register_r1_9 = 32'h580;
parameter register_r1_10 = 32'h600;
parameter register_r1_11 = 32'h680;
parameter register_r1_12 = 32'h700;
parameter register_r1_13 = 32'h780;
parameter register_r1_14 = 32'h800;
parameter register_r1_15 = 32'h880;
parameter register_r1_16 = 32'h900;
parameter register_r1_17 = 32'h980;
parameter register_r1_18 = 32'ha00;
parameter register_r1_19 = 32'ha80;
parameter register_r1_20 = 32'hb00;
parameter register_r1_21 = 32'hb80;
parameter register_r1_22 = 32'hc00;
parameter register_r1_23 = 32'hc80;
parameter register_r1_24 = 32'hd00;
parameter register_r1_25 = 32'hd80;
parameter register_r1_26 = 32'he00;
parameter register_r1_27 = 32'he80;
parameter register_r1_28 = 32'hf00;
parameter register_r1_29 = 32'hf80;
parameter register_r1_30 = 32'h1000;
parameter register_r1_31 = 32'h1080;
parameter register_r1_32 = 32'h1100;
parameter register_r1_33 = 32'h1180;
parameter register_r1_34 = 32'h1200;
parameter register_r1_35 = 32'h1280;
parameter register_r1_36 = 32'h1300;
parameter register_r1_37 = 32'h1380;
parameter register_r1_38 = 32'h1400;
parameter register_r1_39 = 32'h1480;
parameter register_r1_40 = 32'h1500;
parameter register_r1_41 = 32'h1580;
parameter register_r1_42 = 32'h1600;
parameter register_r1_43 = 32'h1680;
parameter register_r1_44 = 32'h1700;
parameter register_r1_45 = 32'h1780;
parameter register_r1_46 = 32'h1800;
parameter register_r1_47 = 32'h1880;
parameter register_r1_48 = 32'h1900;
parameter register_r1_49 = 32'h1980;
parameter register_r1_50 = 32'h1a00;
parameter register_r1_51 = 32'h1a80;
parameter register_r1_52 = 32'h1b00;
parameter register_r1_53 = 32'h1b80;
parameter register_r1_54 = 32'h1c00;
parameter register_r1_55 = 32'h1c80;
parameter register_r1_56 = 32'h1d00;
parameter register_r1_57 = 32'h1d80;
parameter register_r1_58 = 32'h1e00;
parameter register_r1_59 = 32'h1e80;
parameter register_r1_60 = 32'h1f00;
parameter register_r1_61 = 32'h1f80;
parameter register_r1_62 = 32'h2000;
parameter register_r1_63 = 32'h2080;
parameter register_r1_64 = 32'h2100;
parameter register_r1_65 = 32'h2180;
parameter register_r1_66 = 32'h2200;
parameter register_r1_67 = 32'h2280;
parameter register_r1_68 = 32'h2300;
parameter register_r1_69 = 32'h2380;
parameter register_r1_70 = 32'h2400;
parameter register_r1_71 = 32'h2480;
parameter register_r1_72 = 32'h2500;
parameter register_r1_73 = 32'h2580;
parameter register_r1_74 = 32'h2600;
parameter register_r1_75 = 32'h2680;
parameter register_r1_76 = 32'h2700;
parameter register_r1_77 = 32'h2780;
parameter register_r1_78 = 32'h2800;
parameter register_r1_79 = 32'h2880;
parameter register_r1_80 = 32'h2900;
parameter register_r1_81 = 32'h2980;
parameter register_r1_82 = 32'h2a00;
parameter register_r1_83 = 32'h2a80;
parameter register_r1_84 = 32'h2b00;
parameter register_r1_85 = 32'h2b80;
parameter register_r1_86 = 32'h2c00;
parameter register_r1_87 = 32'h2c80;
parameter register_r1_88 = 32'h2d00;
parameter register_r1_89 = 32'h2d80;
parameter register_r1_90 = 32'h2e00;
parameter register_r1_91 = 32'h2e80;
parameter register_r1_92 = 32'h2f00;
parameter register_r1_93 = 32'h2f80;
parameter register_r1_94 = 32'h3000;
parameter register_r1_95 = 32'h3080;
parameter register_r1_96 = 32'h3100;
parameter register_r1_97 = 32'h3180;
parameter register_r1_98 = 32'h3200;
parameter register_r1_99 = 32'h3280;
parameter register_r1_100 = 32'h3300;
parameter register_r1_101 = 32'h3380;
parameter register_r1_102 = 32'h3400;
parameter register_r1_103 = 32'h3480;
parameter register_r1_104 = 32'h3500;
parameter register_r1_105 = 32'h3580;
parameter register_r1_106 = 32'h3600;
parameter register_r1_107 = 32'h3680;
parameter register_r1_108 = 32'h3700;
parameter register_r1_109 = 32'h3780;
parameter register_r1_110 = 32'h3800;
parameter register_r1_111 = 32'h3880;
parameter register_r1_112 = 32'h3900;
parameter register_r1_113 = 32'h3980;
parameter register_r1_114 = 32'h3a00;
parameter register_r1_115 = 32'h3a80;
parameter register_r1_116 = 32'h3b00;
parameter register_r1_117 = 32'h3b80;
parameter register_r1_118 = 32'h3c00;
parameter register_r1_119 = 32'h3c80;
parameter register_r1_120 = 32'h3d00;
parameter register_r1_121 = 32'h3d80;
parameter register_r1_122 = 32'h3e00;
parameter register_r1_123 = 32'h3e80;
parameter register_r1_124 = 32'h3f00;
parameter register_r1_125 = 32'h3f80;
parameter register_r1_126 = 32'h4000;
parameter register_r1_127 = 32'h4080;
parameter register_r1_128 = 32'h4100;
parameter register_r1_129 = 32'h4180;
parameter register_r1_130 = 32'h4200;
parameter register_r1_131 = 32'h4280;
parameter register_r1_132 = 32'h4300;
parameter register_r1_133 = 32'h4380;
parameter register_r1_134 = 32'h4400;
parameter register_r1_135 = 32'h4480;
parameter register_r1_136 = 32'h4500;
parameter register_r1_137 = 32'h4580;
parameter register_r1_138 = 32'h4600;
parameter register_r1_139 = 32'h4680;
parameter register_r1_140 = 32'h4700;
parameter register_r1_141 = 32'h4780;
parameter register_r1_142 = 32'h4800;
parameter register_r1_143 = 32'h4880;
parameter register_r1_144 = 32'h4900;
parameter register_r1_145 = 32'h4980;
parameter register_r1_146 = 32'h4a00;
parameter register_r1_147 = 32'h4a80;
parameter register_r1_148 = 32'h4b00;
parameter register_r1_149 = 32'h4b80;
parameter register_r1_150 = 32'h4c00;
parameter register_r1_151 = 32'h4c80;
parameter register_r1_152 = 32'h4d00;
parameter register_r1_153 = 32'h4d80;
parameter register_r1_154 = 32'h4e00;
parameter register_r1_155 = 32'h4e80;
parameter register_r1_156 = 32'h4f00;
parameter register_r1_157 = 32'h4f80;
parameter register_r1_158 = 32'h5000;
parameter register_r1_159 = 32'h5080;
parameter register_r1_160 = 32'h5100;
parameter register_r1_161 = 32'h5180;
parameter register_r1_162 = 32'h5200;
parameter register_r1_163 = 32'h5280;
parameter register_r1_164 = 32'h5300;
parameter register_r1_165 = 32'h5380;
parameter register_r1_166 = 32'h5400;
parameter register_r1_167 = 32'h5480;
parameter register_r1_168 = 32'h5500;
parameter register_r1_169 = 32'h5580;
parameter register_r1_170 = 32'h5600;
parameter register_r1_171 = 32'h5680;
parameter register_r1_172 = 32'h5700;
parameter register_r1_173 = 32'h5780;
parameter register_r1_174 = 32'h5800;
parameter register_r1_175 = 32'h5880;
parameter register_r1_176 = 32'h5900;
parameter register_r1_177 = 32'h5980;
parameter register_r1_178 = 32'h5a00;
parameter register_r1_179 = 32'h5a80;
parameter register_r1_180 = 32'h5b00;
parameter register_r1_181 = 32'h5b80;
parameter register_r1_182 = 32'h5c00;
parameter register_r1_183 = 32'h5c80;
parameter register_r1_184 = 32'h5d00;
parameter register_r1_185 = 32'h5d80;
parameter register_r1_186 = 32'h5e00;
parameter register_r1_187 = 32'h5e80;
parameter register_r1_188 = 32'h5f00;
parameter register_r1_189 = 32'h5f80;
parameter register_r1_190 = 32'h6000;
parameter register_r1_191 = 32'h6080;
parameter register_r1_192 = 32'h6100;
parameter register_r1_193 = 32'h6180;
parameter register_r1_194 = 32'h6200;
parameter register_r1_195 = 32'h6280;
parameter register_r1_196 = 32'h6300;
parameter register_r1_197 = 32'h6380;
parameter register_r1_198 = 32'h6400;
parameter register_r1_199 = 32'h6480;
parameter register_r1_200 = 32'h6500;
parameter register_r1_201 = 32'h6580;
parameter register_r1_202 = 32'h6600;
parameter register_r1_203 = 32'h6680;
parameter register_r1_204 = 32'h6700;
parameter register_r1_205 = 32'h6780;
parameter register_r1_206 = 32'h6800;
parameter register_r1_207 = 32'h6880;
parameter register_r1_208 = 32'h6900;
parameter register_r1_209 = 32'h6980;
parameter register_r1_210 = 32'h6a00;
parameter register_r1_211 = 32'h6a80;
parameter register_r1_212 = 32'h6b00;
parameter register_r1_213 = 32'h6b80;
parameter register_r1_214 = 32'h6c00;
parameter register_r1_215 = 32'h6c80;
parameter register_r1_216 = 32'h6d00;
parameter register_r1_217 = 32'h6d80;
parameter register_r1_218 = 32'h6e00;
parameter register_r1_219 = 32'h6e80;
parameter register_r1_220 = 32'h6f00;
parameter register_r1_221 = 32'h6f80;
parameter register_r1_222 = 32'h7000;
parameter register_r1_223 = 32'h7080;
parameter register_r1_224 = 32'h7100;
parameter register_r1_225 = 32'h7180;
parameter register_r1_226 = 32'h7200;
parameter register_r1_227 = 32'h7280;
parameter register_r1_228 = 32'h7300;
parameter register_r1_229 = 32'h7380;
parameter register_r1_230 = 32'h7400;
parameter register_r1_231 = 32'h7480;
parameter register_r1_232 = 32'h7500;
parameter register_r1_233 = 32'h7580;
parameter register_r1_234 = 32'h7600;
parameter register_r1_235 = 32'h7680;
parameter register_r1_236 = 32'h7700;
parameter register_r1_237 = 32'h7780;
parameter register_r1_238 = 32'h7800;
parameter register_r1_239 = 32'h7880;
parameter register_r1_240 = 32'h7900;
parameter register_r1_241 = 32'h7980;
parameter register_r1_242 = 32'h7a00;
parameter register_r1_243 = 32'h7a80;
parameter register_r1_244 = 32'h7b00;
parameter register_r1_245 = 32'h7b80;
parameter register_r1_246 = 32'h7c00;
parameter register_r1_247 = 32'h7c80;
parameter register_r1_248 = 32'h7d00;
parameter register_r1_249 = 32'h7d80;
parameter register_r1_250 = 32'h7e00;
parameter register_r1_251 = 32'h7e80;
parameter register_r1_252 = 32'h7f00;
parameter register_r1_253 = 32'h7f80;
parameter register_r1_254 = 32'h8000;
parameter register_r1_255 = 32'h8080;
parameter memory_adress_end = 32'h8080;
